# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bGTv7j-gEEp_LZQs_aw6P61KPmqa_aOO
"""

import pandas as pd
import numpy as np

dat=pd.read_csv('/content/application_record.csv')

dat.shape

dat.isnull()

dat.describe()

dat.info()

import seaborn as sb
import matplotlib.pyplot as plt

dat["OCCUPATION_TYPE"].fillna("Sales staff", inplace = True)

sb.boxplot(data=dat)

dat.info()

cr=dat.corr()

sb.heatmap(cr,annot=True)

sb.boxplot(data=dat)

sb.pairplot(dat.corr())

